name: Download depot
on:
  workflow_dispatch:
    inputs:
      depotId:
        description: 'Depot ID'
        required: true
        type: string
      manifestId:
        description: 'Manifest ID'
        required: true
        type: string
      gitBranch:
        description: 'Git branch'
        required: true
        type: string

run-name: Download depot 730 ${{ github.event.inputs.depotId }} ${{ github.event.inputs.manifestId }} on branch ${{ github.event.inputs.gitBranch }}

concurrency:
  group: ${{ github.event.inputs.depotId }}-${{ github.event.inputs.manifestId }}-${{ github.event.inputs.gitBranch }}
  cancel-in-progress: false

env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

  DEPOT_ID: ${{ github.event.inputs.depotId }}
  MANIFEST_ID: ${{ github.event.inputs.manifestId }}

  METADATA_GIT_URL: https://github.com/cs2-analysis/deports.git
  GIT_NAME: cs2-anal
  GIT_EMAIL: 187910277+cs2-anal@users.noreply.github.com
  GIT_BRANCH: ${{ github.event.inputs.gitBranch }}

  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.prepare.outputs.files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare file list
        id: prepare
        run: |
          cs analysis
          ./prepare.sh
  
  analyze:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        file: ${{ fromJSON(needs.prepare.outputs.files) }}
    name: Analyze ${{ matrix.file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash
      
      - name: Setup IDA Pro
        uses: cs2-analysis/setup-ida-pro@v1
        with:
          download-link: ${{ secrets.IDA_DOWNLOAD_LINK_LINUX }}
          overlay-links: ${{ secrets.IDA_OVERLAY_LINKS_LINUX }}
          install-command: ${{ secrets.IDA_INSTALL_COMMAND_LINUX }}

      - name: Setup BinDiff
        uses: cs2-analysis/setup-bindiff@v1
      
      - name: Run analysis
        run: |
          cs analysis
          ./analyze.sh ${{ matrix.file }}
      