name: Download depot
on:
  workflow_dispatch:
    inputs:
      depotId:
        description: 'Depot ID'
        required: true
        type: string
      manifestId:
        description: 'Manifest ID'
        required: true
        type: string
      gitBranch:
        description: 'Git branch'
        required: true
        type: string
      noAnalyze:
        description: 'Do not analyze'
        required: false
        type: boolean
        default: false

run-name: Download depot 730 ${{ inputs.depotId }} ${{ inputs.manifestId }} on branch ${{ inputs.gitBranch }}

concurrency:
  group: ${{ inputs.depotId }}-${{ inputs.gitBranch }}
  cancel-in-progress: false

env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

  APP_ID: 730
  DEPOT_ID: ${{ inputs.depotId }}
  MANIFEST_ID: ${{ inputs.manifestId }}

  METADATA_GIT_URL: https://github.com/cs2-analysis/deports.git
  GIT_NAME: cs2-anal
  GIT_EMAIL: 187910277+cs2-anal@users.noreply.github.com
  GIT_BRANCH: ${{ inputs.gitBranch }}

  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Steam Depot Downloader
        uses: cs2-analysis/setup-steam-depot-downloader@v1

      - name: Install manifest-grabber
        run: npm install -g https://github.com/cs2-analysis/manifest-grabber

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash
      
      - name: Setup git auth
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global credential.https://github.com/.helper "! f() { echo username=token; echo password=${{ secrets.GIT_TOKEN }}; };f"

      - name: Enable bbr
        run: |
          sudo sysctl -w net.ipv4.tcp_congestion_control=bbr
          sudo sysctl -w net.core.default_qdisc=fq
          
      - name: Run downloader
        working-directory: update
        run: ./update/run.sh

      - name: Wait a bit
        if: ${{ !inputs.noAnalyze }}
        run: sleep 5

      - name: Analyze
        if: ${{ !inputs.noAnalyze }}
        uses: ./.github/workflows/analyze.yml@master
        with:
          depotId: ${{ inputs.depotId }}
          manifestId: ${{ inputs.manifestId }}
          gitBranch: ${{ inputs.gitBranch }}